FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD SpringCloudDemo-config-server-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 9081
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
